### PR TITLE
Fix remaining PHPCS issues

### LINKED ISSUE #32: byline type and URL slug should not be tightly coupled
Right now, a byline of type `author` will always result in a URL like `/author/foo-bar`, and there's no way to filter it. I see that `fm_bylines_filter_rewrite_slug` exists, but it doesn't really work.

### PR DESCRIPTION
**Pull request by ethitter**
Depends on #39. 

Closes #36 by switching to `fm_get_context()` rather than fixing PHPCS issues in `FM_Bylines_Post::set_context()`.

### CODE REVIEW

File: fieldmanager-bylines.php [hunk 1]
```diff
@@ -1,40 +1,42 @@
...
 /**
- * @package Bylines
- * @subpackage Plugin
- * @version 0.2
+ * Plugin Name: Fieldmanager Bylines
+ * Plugin URI: http://github.com/alleyinteractive/fieldmanager-bylines
+ * Description: Allow creation of guest accounts to serve as Authors, Editors, Illustrators etc for a post.
+ * Author: Will Gladstone, David Herrera, Matt Boynes, Erick Hitter
+ * Version: 0.3
+ * Author URI: http://www.alleyinteractive.com/
```
Comment (kevinfodness) [inline fieldmanager-bylines.php]: `https`

File: fieldmanager-bylines.php [hunk 2]
```diff
@@ -1,40 +1,42 @@
...
-Plugin URI: http://github.com/alleyinteractive/fieldmanager-bylines
-Description: Allow creation of guest accounts to serve as Authors, Editors, Illustrators etc for a post.
-Author: Will Gladstone, David Herrera, Matt Boynes
-Version: 0.2
-Author URI: http://www.alleyinteractive.com/
-*/
 
-require_once( dirname( __FILE__ ) . '/php/class-plugin-dependency.php' );
+// Plugin Dependencies handler.
+require_once dirname( __FILE__ ) . '/php/class-fm-bylines-plugin-dependencies.php';
```
Comment (kevinfodness) [inline fieldmanager-bylines.php]: Global: Why not just `__DIR__`?

File: php/class-fm-bylines-author.php [hunk 3]
```diff
@@ -1,17 +1,35 @@
...
 
+	/**
+	 * Class FM_Bylines_Author
+	 */
 	class FM_Bylines_Author extends FM_Bylines_Post {
-
+		/**
+		 * The one true author object
+		 *
+		 * @var object
```
Comment (kevinfodness) [inline php/class-fm-bylines-author.php]: You can make this more specific with `@var FM_Bylines_Author` which helps with IDE type checking.

File: php/class-fm-bylines-author.php [hunk 4]
```diff
@@ -103,14 +114,22 @@ public function early_transition_post_status( $new_status, $old_status, $post )
...
 			return array();
 		}
 	}
 }
 
-function FM_Bylines_Author() {
+/**
+ * FM Bylines Author instance
+ *
+ * @return object
```
Comment (kevinfodness) [inline php/class-fm-bylines-author.php]: Same as above.

File: php/class-fm-bylines-author.php [hunk 5]
```diff
@@ -1,17 +1,35 @@
...
+		 * The one true author object
+		 *
+		 * @var object
+		 */
 		private static $instance;
 
+		/**
+		 * Silence is golden
+		 */
 		private function __construct() {
```
Comment (kevinfodness) [inline php/class-fm-bylines-author.php:24]: If you _really_ want to prevent object instantiation through any method other than `instance()` you also need to apply this pattern to `__clone()` and `__wakeup()`.

File: php/class-fm-bylines-post.php [hunk 6]
```diff
@@ -2,25 +2,48 @@
...
-
+	/**
+	 * Class FM_Bylines_Post
+	 */
 	class FM_Bylines_Post extends FM_Bylines {
-
+		/**
+		 * The one true object
+		 *
+		 * @var object
```
Comment (kevinfodness) [inline php/class-fm-bylines-post.php]: See above.

File: php/class-fm-bylines-post.php [hunk 7]
```diff
@@ -248,32 +287,22 @@ public function set_byline_rewrite_rules() {
...
+			return fm_get_context();
 		}
 	}
 }
 
-function FM_Bylines_Post() {
+/**
+ * FM Bylines Post instance
+ *
+ * @return object
```
Comment (kevinfodness) [inline php/class-fm-bylines-post.php]: Same.

File: php/class-fm-bylines.php [hunk 8]
```diff
@@ -1,28 +1,48 @@
...
-
+	/**
+	 * Class FM_Bylines
+	 */
 	class FM_Bylines {
-
+		/**
+		 * The one true object
+		 *
+		 * @var object
```
Comment (kevinfodness) [inline php/class-fm-bylines.php]: See above.

File: php/class-fm-bylines.php [hunk 9]
```diff
@@ -812,12 +881,18 @@ public function write_byline( $bylines, $before = null, $separator = null, $fina
...
+			return $byline;
 		}
 	}
 }
 
-function FM_Bylines() {
+/**
+ * FM Bylines instance
+ *
+ * @return object
```
Comment (kevinfodness) [inline php/class-fm-bylines.php]: Same.

**Review by kevinfodness — APPROVED** [review]
A few suggestions, but no blockers. :sushi:
